version: '3.9'

services:
  short-url:
    build: .
    deploy:
      replicas: 1
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://short-url-db:5432/short-url"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "example"
    ports:
      - "8080:8080"
  db:
    container_name: "short-url-db"
    image: postgres:12.3
    environment:
      - POSTGRES_DB=short-url
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
