CREATE TABLE short_url(
    short VARCHAR(16) NOT NULL PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,

    created_at TIMESTAMP(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_access TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)